steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'apps/web'

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'apps/web'
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'apps/web/app.yaml']

options:
  logging: CLOUD_LOGGING_ONLY