version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: gomath-postgres
    environment:
      POSTGRES_DB: gomath
      POSTGRES_USER: gomath
      POSTGRES_PASSWORD: gomath123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gomath-network

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: gomath-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gomath-network

  # MinIO 객체 저장소
  minio:
    image: minio/minio:latest
    container_name: gomath-minio
    environment:
      MINIO_ROOT_USER: gomath
      MINIO_ROOT_PASSWORD: gomath123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - gomath-network

  # API 서버 (개발용)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: gomath-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://gomath:gomath123@postgres:5432/gomath
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: gomath
      MINIO_SECRET_KEY: gomath123
      JWT_SECRET: your-jwt-secret-key-here
      CORS_ORIGIN: http://localhost:3000,http://localhost:19006
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    networks:
      - gomath-network
    restart: unless-stopped

  # 웹 애플리케이션 (개발용)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    container_name: gomath-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:3001/graphql
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - ./packages:/packages
      - /app/node_modules
      - /app/.next
    networks:
      - gomath-network
    restart: unless-stopped

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: gomath-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
    networks:
      - gomath-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  gomath-network:
    driver: bridge